services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
    networks:
      - web-public
      - backend-internal

  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: seguranca
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend-internal

  backend:
    build: ./backend
    image: ricciow/embarcados:latest
    container_name: backend_python_embarcados
    depends_on:
      - mosquitto
      - postgres
    restart: unless-stopped
    networks:
      - web-public
      - backend-internal

networks:
  web-public:
    external: true
  backend-internal:
    driver: bridge

volumes:
  postgres_data: